canton.participants.sandbox.ledger-api.port = 10000
canton.participants.sandbox.ledger-api.address = "0.0.0.0"
canton.participants.sandbox.admin-api.port = 10001
canton.participants.sandbox.admin-api.address = "0.0.0.0"
canton.participants.sandbox.http-ledger-api.port = 10002
canton.participants.sandbox.http-ledger-api.address = "0.0.0.0"
canton.sequencers.sequencer1.public-api.port = 10003
canton.sequencers.sequencer1.public-api.address = "0.0.0.0"
canton.sequencers.sequencer1.admin-api.port = 10004
canton.sequencers.sequencer1.admin-api.address = "0.0.0.0"
canton.mediators.mediator1.admin-api.port = 10005
canton.mediators.mediator1.admin-api.address = "0.0.0.0"
