canton {
  participants {
    sandbox {
      storage.type = memory
      ledger-api {
        port = 6865
        address = "0.0.0.0"
      }
      admin-api {
        port = 6866
        address = "0.0.0.0"
      }
    }
  }
  domains {
    local {
      storage.type = memory
      public-api {
        port = 6868
        address = "0.0.0.0"
      }
      admin-api {
        port = 6869
        address = "0.0.0.0"
      }
    }
  }
}
